#!/bin/bash

SKIP_RETRIES=${SKIP_RETRIES:-10}

cleanup() {
  echo::nok Clean up
  net::firewall_stop
  net::pppoe_stop
  echo::ok "  -> Done"
}

finally() {
  local status=$?
  cleanup
  exit $status
}

trap finally 0

source ./echo_utils.bash
source ./process_utils.bash
source ./network_utils.bash
source ./jailbreak_utils.bash

net::firewall_stop
net::pppoe_start

jailbreak::detect_goldhen
goldhen_found=$?

# net::pppoe_stop

if [[ $goldhen_found == 0 ]]
then
  echo::nok Goldhen Not Detected
  ./run-jailbreak
else
  echo::ok Goldhen Detected: Skipping Jailbreak
fi

# Configure network sharing after PPPwned
echo::ok "****************"
echo::ok "Internet Sharing"
echo::ok "****************"

# ip addr add 192.168.2.1/24 dev $INTERFACE
net::wait_conn
net::firewall_start
net::pppoe_start

ppp=$(ip link | grep ": ppp" | cut -d : -f2)

# Wait for a client
echo::nok Waiting PPPOE Connection
while [[ ! $(ip link show $ppp) ]]
do
    sleep 10
done
echo::ok "Console Connected!"

# Quit when the client disconnects
# TODO add some retries here
while [[ $(ip link show $ppp) ]]
do
    echo -n .
    sleep 10
done
echo::nok "Connection Closed"
